version: 2.1

orbs:
  maven: circleci/maven@1.0.1

executors:
  machine:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  validate-maven-installation:
    executor: machine
    steps:
      - run:
          name: Send coverage to CodeCov
          command: |
            if [[ $(command -v mvn) == "" ]]; then
              echo " Maven is not installed "; exit 1;
            else
              echo Maven successfully installed.
            fi
  perform-unit-tests:
    executor: machine
    steps:
      - checkout

      - maven/with_cache:
          steps:
            - run:
                name: Run Tests
                command: mvn clean test --batch-mode

      - maven/process_test_results

      - store_artifacts:
          path: target/*.jar

      - run:
          name: Upload coverage results to CodeCov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  maven_test:
    jobs:
      - validate-maven-installation

      - perform-unit-tests:
          requires:
            validate-maven-installation



